name = "abusebin"
main = ".next/worker/index.js"
compatibility_date = "2025-10-23"
type = "javascript"

account_id = "7b8ae72982e33767d02052569836e58b"
workers_dev = true

[build]
command = "npm run build"
upload_format = "service-worker"

[build.upload]
dir = ".next"
main = "worker/index.js"
