import type { User } from "./user" // Assuming User is declared in a separate file

const mockUsers: User[] = [
  {
    id: "1",
    username: "wounds",
    email: "wounds@example.com",
    password: "feddingzone",
    role: "Admin",
    avatar: "./public/images/design-mode/ezqzq0.png",
    bio: "@rapingteenagers on dc",
    createdAt: new Date("2001-09-11"),
    joinedAt: new Date("2001-09-11"),
    lastSeen: new Date(),
    isOnline: false,
    banned: false,
    nameColor: undefined,
    followers: [],
    following: [],
  },
  {
    id: "2",
    username: "ic3",
    email: "ic3@example.com",
    password: "ACK071675",
    role: "Admin",
    avatar: "./public/images/design-mode/ezqzq0.png",
    bio: "your scent is poison and it's fucking my lungs",
    createdAt: new Date("2019-08-25"),
    joinedAt: new Date("2019-08-25"),
    lastSeen: new Date(),
    isOnline: false,
    banned: false,
    nameColor: undefined,
    followers: [],
    following: [],
  },
  {
    id: "3",
    username: "slit",
    email: "slit@example.com",
    password: "extortionzone",
    role: "Manager",
    avatar: "./public/images/design-mode/ezqzq0.png",
    bio: "looooooool",
    createdAt: new Date(),
    joinedAt: new Date(),
    lastSeen: new Date(),
    isOnline: false,
    banned: false,
    nameColor: undefined,
    followers: [],
    following: [],
  },
  {
    id: "4",
    username: "dismayings",
    email: "dismayings@example.com",
    password: "vile.shosintchallenge",
    role: "Admin",
    avatar: "./public/images/design-mode/ezqzq0.png",
    bio: "junkjaw",
    createdAt: new Date(),
    joinedAt: new Date(),
    lastSeen: new Date(),
    isOnline: true,
    banned: false,
    nameColor: undefined,
    followers: [],
    following: ["1"],
  },
  {
    id: "5",
    username: "bribe",
    email: "bribe@example.com",
    password: "BribeST1414",
    role: "Admin",
    avatar: "./public/images/design-mode/ezqzq0.png",
    bio: "loooserrrr",
    createdAt: new Date(),
    joinedAt: new Date(),
    lastSeen: new Date(),
    isOnline: false,
    banned: false,
    nameColor: undefined,
    followers: [],
    following: ["1"],
  },
]
